// AUTO-GENERATED by dev-orchestrator.js - DO NOT EDIT
export const MF_CONFIG = {
  "TASK_MANAGER": {
    "url": "http://localhost:3002/src/main.tsx",
    "type": "react",
    "name": "@apps/test-task-manager",
    "mode": "dev"
  },
  "ANALYTICS": {
    "url": "http://localhost:3010/main.js",
    "type": "angular",
    "name": "@apps/test-analytics",
    "mode": "dev"
  }
} as const;
export type MFKey = keyof typeof MF_CONFIG;
